services:
  - type: web
    name: controle-passe-uber
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: APP_PIN
        sync: false
